TITEL = "Bell Labs"

CONTENT = ("-ist eine langjährige Forschungs- und Entwicklungsabteilung der „American Telephone and Telegraph Company“ (AT&T)\n"
	"-gehört heute zum finnischen Telekommunikationsunternehmen Nokia\n"
	"-Hauptsitz befindet sich in Murray Hill, New Jersey\n"
	"Geschichte:\n"
	"-gegründet wurde es im Jahr 1925 als Tochtergesellschaft von AT&T unter dem Namen „Bell Telephone Laboratories, Inc“\n"
	"-die Ursprünge reichen mindestens bis 1907 zurück, als die Ingenieurabteilungen von AT&T und der „Western Electric Company“ in New York City zentralisiert wurden\n"
	"-weitere Wurzeln können bis 1883 zurückverfolgt werden, wo auch das „Mechanical Department“ von AT&T gegründet wurde\n"
	"Hauptaktivitäten:\n"
	"-hatte die Aufgabe Telekommunikationsgeräte und -systeme für AT&T zu entwickeln\n"
	"-nebenbei engagierte es sich in Telekommunikation in einem breiten Spektrum von Grundlagen- und angewandter Forschung\n"
	"Innovationen und Errungenschaften:\n"
	"-Seit der Gründung hat die Organisation Tausende wissenschaftliche und technische Innovationen hervorgebracht\n"
    "-1926: Entwicklung des ersten synchronen Tonsystems für Kinofilme\n"
    "-1937: Bau des ersten elektrischen Relais-Digitalcomputers\n"
    "-Clinton Davisson von Bell Labs teilte sich 1937 den Nobelpreis für Physik und zeigte, dass Elektronen sowohl Wellen- als auch Teilcheneigenschaften aufweisen\n"
    "-1947: Erfindung des Transistors, wofür die Forscher John Bardeen, Walter H. Brattain und William B. Shockley 1956 den Nobelpreis für Physik erhielten\n"
    "-In den 1960er Jahren entwickelte Bell Labs das erste elektronische Telefonvermittlungssystem und entwarf Telstar, was das weltweit erste Satellitenkommunikationssystem war\n"
    "-1978: Arno Penzias und Robert W. Wilson von Bell Labs erhielten den Nobelpreis für die Entdeckung der kosmischen Hintergrundstrahlung\n"
    "-leistete Pionierarbeit in der Entwicklung von Sonar, Lasern und Solarzellen und führte verteidigungsbezogene Forschung unter militärischen Verträgen durch\n"
	"Quellen:\n"
		"- https://www.britannica.com/topic/Bell-Laboratories\n")

IMAGE_NAME = ""