TITEL = "Weizenbaum-Institut"
CONTENT = ("-In Andenken an den Verstorbenen deutschen Informatiker und Pionier der künstlichen Intelligenz, wurde 2017 das Weizenbaum-Institut für die vernetzte Gesellschaft gegründet. \n"
"-Der Hauptsitz des Instituts liegt in Berlin. \n"
"-Dem Verbund gehören viele Universitäten, wie die technische Universität Berlin, die Freie Universität Berlin und die Universität Potsdam. \n"
"-Ziel des Instituts ist es Veränderungen im Zusammenhang der Digitalisierung zu untersuchen und wirtschaftliche Handlungsoptionen zu entwickeln. \n"
"-Dabei wollen sie unabhängig und interdisziplinär handeln und den digitalen Wandel auf ökonomisch oder ethischer Ebene erforschen. \n"
"-Im Frühjahr 2021 wurde eine engere Zusammenarbeit mit dem Bayerischen Forschungsinstitut für Digitale Transformation eingegangen, um den wissenschaftlichen Nachwuchs besser zu fördern. \n"
"-Ab November 2021 ging das Institut mit der Online-Zeitschrift The Weizenbaum Journal of the Digital Society (kurz WJDS) online, um der Gesellschaft die Probleme und Lösungsansätze der Digitalisierung vorzuweisen. \n\n"
"Quellen: \n"
"https://www.weizenbaum-institut.de/institut/")