TITEL = "World Wide Web Technologies Consortium (W3C)"

CONTENT = ("Das World Wide Web Consortium (W3C) wurde 1994 von Tim Berners-Lee gegründet, um die Standardisierung von "
           "Techniken im Bereich der World Wide Web-Technologien zu fördern. Ziel war es, die inkonsistente Nutzung "
           "von HTML, HTTP und URI zu verhindern. Heute setzt sich W3C aus 400 Mitgliedern, 50 Mitarbeitern und über "
           "12.000 beteiligten Entwicklern weltweit zusammen.\n\n"

           "### Bedeutende technische Standards\n"
           "**1995:** Graphics, HTML, Style\n"
           "**1996:** Math, XML\n"
           "**1997:** DOM, Patentpolitik, Datenschutz, Synchronisierte Medien, WAI\n"
           "**1998:** Internationalisierung\n"
           "**1999:** Voice Browser\n"
           "**2000:** URI\n"
           "**2001:** Geräteunabhängigkeit, Semantic Web, XML-Schlüsselverwaltung, Qualitätssicherung\n"
           "**2002:** Multimodale Interaktion, Webdienste\n"
           "**2003:** XForms\n"
           "**2004:** Zusammengesetzte Dokumentenformate\n"
           "**2005:** XML Signature Syntax and Processing 1.1\n"
           "**2006:** Mobile Web Best Practices 1.0\n"
           "**2007:** OWL 2 (Web Ontology Language)\n"
           "**2008:** SPARQL Query Language for RDF, HTML 5 (erste Arbeitsentwürfe)\n"
           "**2010:** HTML5 (W3C empfiehlt HTML5)\n"
           "**2011:** CSS3 (Cascading Style Sheets Level 3)\n"
           "**2012:** HTML5.1 (W3C empfiehlt HTML5.1)\n"
           "**2014:** HTML 5.1 Second Edition (aktualisierte Empfehlung)\n"
           "**2016:** Web Content Accessibility Guidelines (WCAG) 2.1\n"
           "**2017:** HTML 5.2, Web of Things (WoT) Architecture\n"
           "**2018:** Web Authentication: An API for accessing Public Key Credentials Level 1\n"
           "**2019:** Web of Things (WoT) Thing Description\n"
           "**2020:** CSS Grid Layout Level 2, Web of Things (WoT) Scripting API\n"
           "**2021:** CSS Scroll Snap Module Level 1\n"
           "**2022:** WebRTC (Web Real-Time Communications) Next Version (1.0), HTML Living Standard (laufende "
           "Aktualisierung)\n\n"

           "### Quellen:\n"
           "About us (o. D.): W3C, [online] https://www.w3.org/about/.")

IMAGE_NAME = "W3C.svg"

CONNECTIONS = ["WORLD_WIDE_WEB", "TIM_BERNERS_LEE", "HTML", "HTTP", "URI"]
