TITEL = "Zuse KG"
CONTENT =("-Gegründet wurde die Zuse KG 1949 von Konrad Zuse (als Komplementär) in Neukirchen \n"
"-zusätzlich gab es noch zwei weitere Mitbegründer: \n"
"   -Alfred Eckhard, der bereits mit Konrad gearbeitet hatte. In der Firma war Alfred MIT-Komplementär. \n"
"	-Harro Strucken war Kommanditist \n"
"-Die Zuse KG war der erfolgreichste Computerhersteller Deutschlands zu der Zeit, da die anderen Hersteller technologisch noch nicht so weit waren. \n"
"-Das Unternehmen entwickelte die Zuse Z5, Z11 und später dann auch serienmäßige Universalrechner (z.B. Z22, Z23, Z25), aber auch das Peripheriegerät den Z64 Graphomat, ein automatischer Zeichentisch, der automatisch technische Zeichnungen erstellte. \n"
"-Die Zuse KG bekam mehrere große Aufträge, wie die Vermietung des Z4 an die Eidgenössische Technische Hochschule Zürich (ETH Zürich) für fünf Jahre, oder die Bestellung eines Großrechners (Z5) im Jahre 1950. \n"
"-Die Firma hatte außerdem einen starken Firmenwachstum, da die Zuse KG 1949 mit 8 Mitarbeitern startete und wuchs auf ungefähr 1200 Mitarbeiter im Jahr 1964. \n"
"-Wegen technischen Problemen bei der Z25 und der erfolglosen Z31, machte die Zuse KG zu starken Verlust, sodass diese 1964 von der Mannheimer BBC AG übernommen wurde. 1969 wurde sie dann vollständig an die Siemens AG verkauft. \n\n"
"### Quellen: \n"
"Stoller, Detlef (2022c): Der erste Computer der Welt: Z3 von Konrad Zuse fand damals kaum Beachtung, ingenieur.de - Jobbörse und Nachrichtenportal für Ingenieure, [online] https://www.ingenieur.de/technik/produkte/konrad-zuses-z3-computer-welt-80/")