TITEL = "Electronic Numerical Integrator and Computer (ENIAC)"

CONTENT = ("ENIAC war der erste turingmächtige Universalcomputer. Er wurde während des Zweiten Weltkrieges von John "
           "Presper Eckert und John William Mauchly im Jahre 1946 an der University of Pennsylvania (USA) entwickelt. "
           "\n\n"
           
           "Verwendung\n"
           "Der ENIAC wurde von der US-Armee für wissenschaftliche und mathematische Zwecke verwendet. Insbesondere "
           "für ballistische Trajektorien, Atomphysik, Wetterprognosen und komplexe mathematische Aufgaben. "
           "Programmiert wurde der ENIAC fast ausschließlich von Frauen, den sogenannten 'ENIAC Frauen'.\n\n"
           
           "Funktionsweise\n"
           "Der ENIAC nutzte mehrere tausend Vakuumröhren als Schlüsselelemente seiner Struktur. Die elektronischen "
           "Schaltkreise des Computers wurden durch diese Vakuumröhren gesteuert und"
           "ermöglichten arithmetische und logische Berechnungen. Da der ENIAC über keinen Befehlsspeicher "
           "verfügte, erfolgte die Programmierung durch physische Umsteckung. Die Ergebnisse wurden extern auf "
           "Lochkarten oder Bandlaufwerken gespeichert. Im Gegensatz zur vergleichbaren Computern basierte der ENIAC "
           "nicht auf dem Dual- sondern auf dem Dezimalsystem. Er konnte in seinem Akkumulator eine 10-stellige "
           "Dezimalzahl speichern und damit die Rechenoperationen Addition, Subtraktion, Division und Multiplikation "
           "sowie das Ziehen von Quadratwurzeln ausführen.\n\n"
           
           "Probleme\n"
           "1. Die Vakuumröhren waren anfällig für Ausfälle, was zu häufigen Unterbrechungen und Reparaturen führte. "
           "Schon der Ausfall einer Röhre führte zu Rechenfehlern\n"
           "2. Die Vakuumröhren haben zu einer erheblichen Wärmeentwicklung geführt. Deshalb waren komplexe "
           "Kühlmechanismen erforderlich, um Überhitzung zu vermeiden.\n"
           "3. ENIAC war riesig und stellte daher logistische Herausforderungen bei der Installation und Wartung dar.\n"
           "4. Die Programmierung erfolgte durch manuelle Umsteckungen und Verkabelungen. Dies war "
           "zeitaufwändig, fehleranfällig und erforderte speziell geschultes Personal.\n"
           "5. Das Ändern von Programmen erforderte erheblichen manuellen Aufwand, da ENIAC auf spezifische "
           "Aufgaben zugeschnitten ist und nicht so leicht für verschiedene Anwendungen umkonfiguriert werden kann.\n"
           
           "Technische Daten\n"
           "Fläche: 10m x 17m\n"
           "Gewicht: 27 Tonnen\n"
           "* 40 parallel arbeitenden Komponenten, je 60 cm breit, 270 cm hoch und 70 cm tief\n"
           "* 17.468 Vakuumröhren\n"
           "* 7.200 Dioden\n"
           "* 1.500 Relais\n"
           "* 70.000 Widerstände\n"
           "* 10.000 Kondensatoren\n"
           "Kosten: 468.000 US-$\n\n"
           
           "Quellen:\n"
           "https://www.nature.com/articles/158500a0\n")

IMAGE_NAME = "ENIAC.gif"
