TITEL = "Linux"

CONTENT = (
    "Kernel:\n"
    "- Herzstück des Linux-Betriebssystems.\n"
    "- Verantwortlich für die Verwaltung von Hardware-Ressourcen und die Ausführung von Prozessen.\n\n"
    "Multiuser- und Multitasking-System:\n"
    "- Erlaubt mehreren Benutzern gleichzeitig auf demselben System zu arbeiten.\n"
    "- Fähigkeit, mehrere Programme gleichzeitig auszuführen.\n\n"
    "Dateisystem:\n"
    "- Strukturierte Organisation von Dateien und Verzeichnissen.\n"
    "- Hierarchische Anordnung ermöglicht effiziente Verwaltung und Navigation.\n\n"
    "Shell:\n"
    "- Befehlszeileninterpreter, der Benutzeranweisungen entgegennimmt.\n"
    "- Ermöglicht die Interaktion mit dem Betriebssystem.\n\n"
    "Benutzerverwaltung und Berechtigungen:\n"
    "- Jeder Benutzer hat ein eigenes Benutzerkonto mit individuellen Berechtigungen.\n"
    "- Steuert den Zugriff auf Dateien und Systemressourcen.\n\n"
    "Netzwerkfähigkeit:\n"
    "- Eingebaute Netzwerkfunktionen ermöglichen die Kommunikation zwischen Rechnern.\n"
    "- Linux kann als Server in Netzwerken dienen.\n\n"
    "Hardwareunterstützung:\n"
    "- Große Palette unterstützter Hardware.\n"
    "- Durch modulare Kernelunterstützung können Treiber dynamisch geladen werden.\n\n"
    "Portabilität:\n"
    "- Linux kann auf verschiedenen Hardwarearchitekturen laufen.\n"
    "- Portabilität ermöglicht die Nutzung auf unterschiedlichen Geräten.\n\n"
    "Paketverwaltung:\n"
    "- System zum Installieren, Aktualisieren und Entfernen von Softwarepaketen.\n"
    "- Vereinfacht die Softwareverwaltung und -aktualisierung.\n\n"
    "Open Source und GPL:\n"
    "- Linux basiert auf Open-Source-Prinzipien.\n"
    "- Die GNU General Public License (GPL) ermöglicht die Freiheit, den Quellcode zu überprüfen, zu modifizieren und zu teilen.\n\n"
    "X Window System:\n"
    "- Verwaltet die Anzeige von Grafiken und Fenstern.\n"
    "- Erlaubt die Nutzung grafischer Benutzeroberflächen (Desktop-Umgebungen).\n\n"
    "Init-System:\n"
    "- Koordiniert den Systemstart und -shutdown.\n"
    "- Übergibt Kontrolle an verschiedene Systemdienste und Anwendungen.\n\n"
    "Security Features:\n"
    "- Zugriffskontrollen, Firewalls und Verschlüsselung bieten Sicherheit.\n"
    "- Sicherheitspatches und regelmäßige Updates sind integraler Bestandteil.\n\n"
    "Community-Entwicklung:\n"
    "- Entwickelt von einer breiten Gemeinschaft von Freiwilligen weltweit.\n"
    "- Gemeinsame Weiterentwicklung durch Kollaboration und Diskussion.\n\n"
    "Flexibilität und Anpassbarkeit:\n"
    "- Modularer Aufbau erlaubt es, nur benötigte Komponenten zu installieren.\n"
    "- Erlaubt die Anpassung an spezifische Anforderungen und Ressourcen.\n\n"
    "Skripting und Automatisierung:\n"
    "- Mächtige Skriptsprachen wie Bash erleichtern die Automatisierung von Aufgaben.\n"
    "- Möglichkeit zur Erstellung von Skripten für komplexe Abläufe.\n\n"
    "Linux zeichnet sich durch seine Flexibilität, Stabilität, Sicherheit und die Möglichkeit zur umfassenden Anpassung aus. \n"
    "Es bildet die Grundlage für zahlreiche Betriebssysteme, Anwendungen und Geräte in der heutigen IT-Landschaft.\n"

"Quellen:\n"
    "https://commons.wikimedia.org/wiki/Category:Linux?uselang=de"
)

IMAGE_NAME = ""
