TITEL = "Programmierbare ICs"

CONTENT = ("-Programmierbare Logik-ICs sind kleine elektronische Komponenten, die für rekonfigurierbare digitale Schaltungen verwendet werden\n"
	"-bei der Herstellung haben sie eine unspezifizierte Funktion im Gegensatz zu integrierten Schaltkreisen (ICs), die aus Gates bestehen und eine spezifische Funktion haben\n"
	"-Hauptarten von programmierbaren Schaltkreisen:\n"
		"1. Complex Programmable Logic Devices (CPLD):\n"
"-Einsatz für komplexe Kombinations- oder sequenzielle Schaltungen\n"
"-bestehen aus logischen Array-Blöcken, programmierbaren Verbindungen und E/A-Blöcken\n"
"2. Field-Programmable Gate Arrays (FPGA):\n"
"-Verwendung in der Prototypenentwicklung anwendungsspezifischer ICs\n"
"-bestehen aus Logikblöcken, programmierbarer Schaltmatrix, E/A-Blöcken und Verbindungen\n"
"3. Simple Programmable Logic Devices (SPLD):\n"
"-kleinste und einfachste programmierbare Logikschaltkreise\n"
"-unterteilt in feste Logikschaltkreise (FLD) und programmierbare Logikschaltkreise (PLD)\n"
	"-Anwendungen von Logik-Schaltungen:\n"
		"-vielseitige Halbleitergeräte für die Leiterplattenmontage\n"
		"-Einsatz in verschiedenen Elektronikanwendungen wie:\n"
			"-Synchronisierung\n"
			"-Bus-Schnittstellen\n"
			"-Decoder\n"
			"-Zähler\n"
	"Quellen:\n"
	"- https://at.rs-online.com/web/c/halbleiter/programmierbare-logik-ics/\n")

IMAGE_NAME = ""