TITEL = "Betriebssystem Unix"

CONTENT = ("Eigenschaften:\n"
	"-bildet die Basis für die Betriebssysteme Linux, macOS und die der meisten Smartphones und Tablets\n"
	"-Unix führte die bekannte hierarchisch aufgebaute Dateisystem und Ordnerstruktur ein\n"
		"-Benutzer können dieses strukturieren\n"
	"-das Root-Verzeichnis wird mit dem Schrägstrich „/“ gekennzeichnet\n"
	"-läuft nach dem Prinzip „Everything is a file“: Laufwerke, Festplatten, Terminals, fremde Rechner sind als Gerätedateien im Dateisystem abgebildet\n"
	"-Unix ermöglich gleichzeitiges Ausführen mehrerer Prozesse\n"
	"-der Scheduler im Betriebssystemkernel verwaltet Prozesse über ein Prioritätensystem\n"
	"-dies ermöglichte mehr Effizienz und Stabilität\n"
	"-war von vornerein als Mehrbenutzersystem konzipiert\n"
	"-jedes Programm und jeder Prozess haben einen Eigentümer\n"
	"-gleichzeitiges Arbeiten wird ermöglicht, was Vorteile in der Ressourcennutzung und Rechtemanagement bietet\n"
	"-4.2BSD (1983) integrierte den Internetprotokollstapel, legte die Grundlage für das Internet und ermöglichte Netzwerkkonfiguration\n"
	"-Unix kann als Client oder Server agieren\n"
	"-verfolgte von Anfang an den Ansatz eines portablen Systems\n"
	"-verwendet die Programmiersprache C\n"
	"-Unix wurde als portables System bekannt, insbesondere ab der stark überarbeiteten Unix-V7-Version (1979).\n"

	"Geschichte:\n"
	"-wurde 1969 als Mehrbenutzer-Betriebssystem entwickelt\n"
	"-Bereitstellung verschiedener Arbeitsumgebungen für mehrere Benutzer am Computer\n"
    "-entstand in „Bell Laboratories“\n"
	"-es wurde für Bildungseinrichtungen freigegeben, was den Aufstieg des neuen Betriebssystems einleitete\n"
	"-galt zunächst als Spielzeug der programmierenden Zunft\n"
	"-Entwicklung begann zunächst mit Assembler, doch mit der Grundstruktur startete das Projekt einer eigenen, höheren Sprache, welche C wurde\n"
	"-der Wert des freigegeben Quellcodes von Kernel und Anwendungen lag nicht nur im Lerneffekt für Entwickler\n"
	"-stellte geringe Hardwareanforderungen und bot hohen Nutzerkomfort\n"
		"-> förderte das Experimentieren und Weiterentwickeln, was Anklang fand an der Universität von Kalifornien in Berkeley (ehemalige Universität von Thompson)\n"
	"-Bill Joy und Chuck Haley (damalige Diplomstudenten) verbesserten das Pascal-System und schufen den Texteditor „ex“, den Vorläufer von „vi“\n"
	"-1977 erschien unter der Leitung von Joy eine modifizierte Unix-Variante, die die bisherigen Verbesserungen einschloss\n"
	"-diese Berkeley Software Distribution (BSD) integrierte später das Netzwerkprotokoll TCP/IP in Unix-Universum\n"
	"-aufgrund der eigenen BSD-Lizenz wurde es als eine der wichtigsten Unix-Abwandlungen anerkannt\n"
	"-die Entwicklung von BSD trug dazu bei dem Konzept eines freien Betriebssystems gerecht zu werden\n"
	"Quellen:\n"
		"- https://it-service.network/it-lexikon/unix#:~:text=Unix%2C%20oder%20auch%20UNIX%2C%20wurde,und%20ihnen%20verschiedene%20Arbeitsumgebungen%20bereitzustellen\n"
		"- https://www.ionos.de/digitalguide/server/knowhow/unix-geschichte-und-grundlagen-des-urgesteins/\n")

IMAGE_NAME = ""