TITEL = "Ada Lovelace (1815-1852)"
CONTENT = ("-Geboren wurde Augusta Ada Byron am 10. Dezember 1815 in London.\n"
"-Ihre Mutter (Isabella Noel-Byron) ließ ihre Tochter eine naturwissenschaftliche Ausbildung einschlagen.\n"
"-Sie bekam Privatunterricht, da es in England nicht erstattet war zu studieren.\n"
"-Mit 17 lernte sie Charles Babbage kennen (er arbeitet zu dieser Zeit an dem „Difference Engine“). Von dort an begann Ada Lovelace mit Charles Babbage an Projekten wie dem Analytic Engine zu entwickeln, welcher nie zu deren Lebenszeit fertiggestellt werden konnte.\n"
"-1833 wurde sie dem König (Wilhelm IV.) vorgestellt.\n"
"-1835 heiratete sie William King, mit dem sie drei Kinder bekamen (Bryon King-Noel, Anne King-Noel und Ralph King-Milbanke (2. Earl of Lovelace)).\n"
"-1838 wurde William zum Earl of Lovelace ernannt, wodurch Ada ihren Namen erhielt.\n"
"-William ließ sich in der Royal Society aufnehmen, um Artikel für seine Frau abzuschreiben, da Ada als Frau kein Zutritt gewährt wurde.\n"
"-1843 erkrankt Ada Lovelace jedoch. Von dort an nimmt sie Opium und Alkohol zu sich und wird depressiv, sodass ihre Kinder bei Adas Mutter aufwachsen.\n"
"-Am 27 November 1852 stirbt Ada Lovelace in einem Alter von 36 Jahren in London. Bis heute steht eine Gedenktafel an ihrem Grab in Hucknall.\n"
"https://www.mpg.de/frauen-in-der-forschung/ada-lovelace \n\n"
"Quellen: \n"
"https://academic.oup.com/jrssig/article/15/5/45/7029269?login=false \n"
"https://www.geo.de/wissen/23430-rtkl-mathematik-computer-pionierin-ada-lovelace-die-frau-die-aus-der-zukunft-kam\n")
IMAGE_NAME = "Ada_Lovelace.jpg"
CONNECTIONS = ["CHARLES_BABBAGE_DATA","ANALYTIC_ENGINE_DATA","ADA_LOVELACE_BEITRAG_DATA"]