TITEL = "Wissenschaftlicher Beitrag von Ada Lovelace"
CONTENT = ("-In einem ihrer Kommentare, erklärte sie, dass es einen Unterschied zwischen einer Rechenmaschine und "
           "einem Computer gibt. Ada erläuterte, dass eine Rechenmaschine nur eine fixe Berechnung durchführen kann, "
           "beziehungsweise auf die manuelle Eingabe der Operation angewiesen ist. Hingegen kann man mithilfe der "
           "Programmierung beliebig komplexe Algorithmen für den Rechner formulieren und automatisch ablaufen lassen. "
           "Diese Notiz, war der erste Grundgedanke des Computers. \n"
           "-Ada Lovelace weist außerdem auf den Unterschied zwischen dem physischen Teil des Computers, welcher aus "
           "materiellen"
           "Dingen, wie Kupferrädern und Lochkarten besteht, und dem symbolischen Teil des Computers, "
           "also die automatischen Berechnungen (Code), hin. Damit legt sie als erste die Unterteilung in Hardware "
           "und Software fest. \n"
           "-Die war eine Pionierin der Wissenschaft und gilt bis heute als Vorbild für viele Frauen, da gerade zu "
           "ihrer Zeit Frauen sehr selten in der Wissenschaft tätig waren. Daher wurde sie von vielen männlichen "
           "Arbeitskollegen nicht gerne akzeptiert, jedoch arbeitete sie trotzdem weiter. \n"
           "-Heute gibt es in Andenken an sie eine Programmiersprache, mit dem Namen ADA. Diese Programmiersprache "
           "wurde Ende der 1970er Jahre entwickelt und stark vom US-Verteidigungsministerium gefördert. Sie ähnelt "
           "Pascal und gilt als höhere Programmiersprache. Es gibt mehrere Versionen, wie zum Beispiel Ada 83, "
           "Ada 95 oder Ada 2012. \n\n"
           
           "### Quellen\n"
           "ADA Lovelace und das erste Computerprogramm der Welt (o. D.): Max-Planck-Gesellschaft, [online] "
           "https://www.mpg.de/frauen-in-der-forschung/ada-lovelace.\n")
