TITEL = "Alan Turing (1912-1954)"

CONTENT = ("Alan Turing, ein britischer Mathematiker, Logiker und Kryptoanalytiker, gilt als einer der Begründer der "
           "Informatik. Durch seine erfolgreiche Entschlüsselung der deutschen Enigma-Verschlüsselungscodes hatte "
           "Turing einen entscheidenden Einfluss auf den Verlauf des Zweiten Weltkriegs. Das von Turing entwickelte, "
           "theoretische Modell eines Allzweckcomputers, der Turing-Maschine, wird heute als Grundlage der Informatik "
           "angesehen. Neben seinen Errungenschaften für die moderne Informations- und Computertechnologie, "
           "war Turing auch im Gebiet der theoretischen Biologie tätig. Seine Theorien werden heute als Grundlage zur "
           "Forschung im Bereich des 'Künstliches Lebens' angesehen.\n\n"

           "### Biographie \n"
           "**1912:** Geboren am 23. Juni 1912 in London, England\n"
           "**1931:** Mathematikstudium am King's College in Cambridge\n"
           "**1935:** Ernennung zum 'Fellow of the college' (Ehrenbezeichnung)\n"
           "**1936-1937:** Veröffentlichung seines ersten und erfolgreichsten Papers 'On Computable Numbers, "
           "with an Application to the Entscheidungsproblem'. Das Paper legte den Grundstein für das Konzept der "
           "Turing-Maschine, einem abstrakten mathematischen Modell einer Rechenmaschine\n"
           "**1938:** Erwerb des Doktorgrades in Mathematischer Logik an der Princeton University in New Jersey (USA) "
           "unter der Leitung von Alonzo Church\n"
           "**1938:** Rückkehr zum King's College in Cambridge\n"
           "**1939:** Wechsel zum Hauptquartier der 'Government Code and Cypher School' (GC&CS) zu Kriegsbeginn. Dort "
           "entwickelte Turing die Turing-Bombe ('Bombes'), eine elektromechanische Maschine zum entziffern von "
           "Funksprüchen, die mit der deutschen Schlüsselmaschine 'Enigma' verschlüsselt wurden.\n"
           "**1945:** Rekrutierung zum 'National Physical Laboratory' (NPL) in London, mit dem Ziel, "
           "einen elektronischen Machines als konkrete Umsetzung der Turing-Maschine zu entwerfen\n"
           "**1948:** Übernahme der stellvertretenden Leitung des 'Royal Society Computing Machine Laboratory' an der "
           "Manchester University\n"
           "**1950:** Fertigstellung Turings erster elektronischen Rechenmaschine (Pilot Model ACE).\n"
           "**1951:** Ernennung zum 'Fellow of the Royal Society of London'\n"
           "**1952:** Strafrechtliche Verfolgung Turings aufgrund seiner Homosexualität und Verurteilung zu einer zwölf"
           "monatigen Hormontherapie\n"
           "**1951:** Arbeit im Bereich der theoretischen Biologie und Entwicklung des Turing-Mechanismus, "
           "der beschrieb, wie Reaktions-Diffusions-Systeme spontan Strukturen entwickeln können\n"
           "**1953:** Entwicklung eines der ersten Schachprogramme 'Turochamp'\n"
           "**1953:** Erkrankung an Depressionen in Folge der Hormonbehandlung\n"
           "**1954:** Suizid am 07. Juni 1954 in Wilmslow, Cheshire\n"
           "**Seit 1966:** Jährliche Verleihung des Turing Award für besondere Entwicklungen in der Informatik durch "
           "die"
           "'Association for Computing Machinery' (ACM)\n"
           "**2013:** Begnadigung Turings durch den sogenannten 'Royal Pardon' am 24. Dezember 2013. Turing gilt "
           "dadurch als offiziell rehabilitiert.\n"
           "\n\n"
           

           "### Quellen\n"
           "AlanTuring.net Bio of Alan Turing (o. D.): [online] "
           "https://www.alanturing.net/turing_archive/pages/Reference%20Articles/Bio%20of%20Alan%20Turing.html.\n"
           "Alan Turing (Stanford Encyclopedia of Philosophy) (2013): [online] "
           "https://plato.stanford.edu/entries/turing/.\n")

IMAGE_NAME = "Alan_Turing.jpg"

CONNECTIONS = ["TURING_AWARD", "ALONZO_CHURCH", "TURING_MACHINE", "BOMBES", "CHURCH_TURING_THESIS"]
