TITEL = "Alonzo Church (1903-1995)"

CONTENT = ("Alonzo Church war ein US-amerikanischer Mathematiker und Logiker, der durch seine Arbeit in den Bereichen "
           "mathematische Logik und theoretische Informatik bekannt wurde. Zusammen mit Alan Turing entwickelte er "
           "die Church-Turing-These, die Aussagen über die Fähigkeit einer Rechenmaschine trifft.\n\n"

           "Biographie:\n"
           "1903: Geboren am 14. Juni 1903 in Washington, D.C., USA\n"
           "1924: Abschluss des Mathematikstudiums an der Princeton University in New Jersey (USA)\n"
           "1927: Erhalt des Doktortitels für seine Dissertation zum Thema 'Alternatives to Zermelo's Assumption'\n"
           "1928: National Research Fellow an der Harvard University sowie an den Universitäten in Göttingen und "
           "Amsterdam.\n"
           "1929: Ernennung zum 'Assistant Professor of Mathematics' an der Princeton University\n"
           "1930er: Entwicklung des Lambda Kalküls, einer formalen Notation zur Darstellung von Funktionen, "
           "die die Grundlage für funktionale ProgrammingLanguages bildet\n"
           "1936: Formulierung des Church Theorems. Church's Theorem besagt, dass es keine allgemeine Methode gibt, "
           "um vorherzusagen, ob ein bestimmter Rechenschritt im Lambda-Kalkül immer zu einem Ergebnis führt oder ob "
           "er in einer endlosen Schleife verbleibt.\n"
           "1936: Formulierung der Church These. Die Church These besagt, dass jede mathematisch berechenbare "
           "Funktion durch das Lambda-Kalkül dargestellt werden kann\n"
           "1936: Übertragung der Church-These auf die von Alan Turing entwickelte Turing-Maschine ("
           "'Church-Turing-These')\n"
           "1939: Beförderung zum 'Associate Professor'\n"
           "1941: Veröffentlichung seines Buches 'The Calculi of Lambda-Conversion' als Zusammenfassung über die "
           "Grundlagen und die Anwendung des Lambda Kalküls\n"
           "1947: Beförderung zum 'Professor'\n"
           "1956: Veröffentlichung seines Buches 'Introduction to Mathematical Logic', welches die Grundlagen der "
           "mathematischen Logik behandelt\n"
           "1961: Ernennung zum 'Professor of Mathematics and Philosophy'\n"
           "1967: Eintritt in den Ruhestand und anschließender Wechsel zur University of California in Los Angeles ("
           "USA). Dort arbeitete er als 'Kent Professor of Philosophy' und 'Professor of Mathematics'\n"
           "1990: Erneuter Eintritt in den Ruhestand\n"
           "1995: Gestorben am 11. August 1995 in Hudson, Ohio, USA\n\n"


           "Quellen:\n"
           "https://mathshistory.st-andrews.ac.uk/Biographies/Church/\n"
           "https://www.britannica.com/biography/Alonzo-Church\n")

IMAGE_NAME = "Alonzo_Church.jpeg"
