from tkinter.tix import IMAGE

TITEL = "Edsger W. Dijkstra (1930-2002)"
CONTENT = ("-Edsger Wybe Dijkstra ist am 11. Mai 1930 in Amsterdam geboren. \n"
"-Er machte sein Abi am Gymnasium Erasmianum in Rotterdam. Danach begann er 1948 an der Universität in Leiden Mathematik und theoretische Physik zu studieren. \n"
"-Nachdem er 1951 seinen Bachelor erhielt, besuchte er einen Programmierkurs an der University of Cambridge. \n"
"-1956 erreichte er dann den Mastergrad in Physik und Mathematik, welchen er dann nach dem Programmierkurs wieder in Leiden fortsetzte. \n"
"-Danach begann er bei dem Mathematisch Centrum (heute Centrum Wiskunde & Informatica/ Zentrum für Mathematik und Informatik) in Amsterdam zu arbeiten. Dort entwickelt er 1959 den Dijkstra-Algorithmus. \n"
"-1957 heiratete er seine Frau Ria, mit der er drei Kinder bekam. \n"
"-1959 schrieb er seine Doktorarbeit über Electrologica X1 des Mathematisch Centrum zu schreiben, bei der er die Grundlegende Software geschrieben hatte, weshalb er als erster niederländische Informatiker gilt. \n"
"-Ende der 1950er war Dijkstra am Entwurf des Algol 60 beteiligt. Dafür stellte er 1960 den Compiler fertig. \n"
"-1962 wurde Dijkstra Professor in Mathematik an der Technischen Hochschule Eindhoven. Später entwickelte er das Multitasking-Betriebssystem THE, welches er nach der Technische Hogeschool Eindhoven, benannte. \n"
"-Von 1971 bis zu seinem Tod erheilt Dijkstra zahlreiche Auszeichungen, wie den Turingaward und wurde sogar Mitglied der Königlich-Niederländischen Akademie der Wissenschaften. \n"
"-Ab 1973 leitete er an der Universität nur noch den Eindhoven Tuesday Afternoon Club, bei dem er mit Kollegen dienstagnachmittags über neue wissenschaftliche Probleme oder Erkenntnisse redete. Denn seine Hauptarbeit bestand nun darin der Research Fellow, also wissenschaftlicher Mitarbeiter, des Bürogeräteherstellers Burroughs Corporation, zu sein. \n"
"-1981 entwickelte Dijkstra das Sortierverfahren, den Smoothsort. \n"
"-1984 wechselte er auf den Schlumberger Centennial Chair in Computer Sciences an der Univerisät von Texas. Auch dort führte er später den Tuesday Afternoon Club fort. \n"
"-2000 wurde er dann emeritiert, also in den Ruhestand versetzt. \n"
"-Am 6. August 2002 starb Edsger Dijkstra in Nuenen an den Folgen von Krebs. \n\n"
"### Quellen: \n"
"Hardison, Erica (2018): Edsger Dijkstra, IEEE Computer Society, [online] "
           "https://www.computer.org/profiles/edsger-dijkstra.\n"
"Edsger W. Dijkstra: Brilliant, colourful, and opinionated (o. D.): [online] "
           "https://www.cwi.nl/en/about/history/e-w-dijkstra-brilliant-colourful-and-opinionated/.")
IMAGE_NAME = "Edsger_Dijkstra.jpg"
CONNECTIONS = ["DIJKSTRA-ALGORITHMUS","ALGOL_60"]