TITEL = "Grace Hopper (1906-1992)"
CONTENT = ("-Am 9. Dezember 1906 wird Grace Brewster Murray in New York City geboren. \n"
           "Universitäre Laufbahn (1928-1943): \n"
           "-1924 begann Grace ihr Studium am Vassar College in Mathematik. \n"
           "-1928 schloss sie ihr Bachelorstudium in Mathematik am Vassar College ab und setzte ihre akademische Ausbildung an der Yale University fort. \n"
           "-1930 erwarb Grace einen Master-Abschluss in Mathematik an der Yale University. \n"
           "-Ebenfalls 1930 heiratete sie Vincent Foster Hopper und nahm seinen Namen an. \n"
           "-1934 promovierte sie an der der gleichen Universität in Mathematik. \n"
           "-1931 bis 1943 lehrt sie am Vassar College Mathematik. \n"
           "-Im Jahr 1943 trat Hopper der US Navy bei. \n"
           "-1944 tritt sie dem Forschungsteam im Computerlabor der Harvard-Universität bei, jedoch gehörte sie bis 1966 als Reserve der US-Marine an. In dem Harvard Labor half sie dem Projektleiter Howard H. Aiken, den ersten voll elektrischen Computer der Geschichte zu bauen: Dem Mark 1. \n"
           "-1945 lassen sich Vincent und Grace scheiden. \n"
           "-Durch ein Insekt (englisch Bug), welches zwischen den elektronischen Schaltern herfliegt, wird der gesamte Computer lahmgelegt. Daher wurde der noch heute bekannte begriff Bug erstmals als Fehler in einem Computerprogramm bezeichnet. \n"
           "-Während des Krieges spielte sie, dank ihrer Pionierarbeit und ihrer Fähigkeiten, eine Schlüsselrolle in der Entwicklung und Nutzung von Computertechnologien für militärische Zwecke. \n"
           "-Grace berechnete außerdem die genauen Winkel der Geschütze auf See, damit die Navy auch bei schlechtem Wetter kampffähig blieb. \n"
           "-1949 verlässt sie die Harvard-Universität und tritt sie der Eckert-Mauchly Computer Kooperation als Mathematikerin bei, wo sie bis 1952 arbeitet. Dieser Kooperation, geleitet von John Mauchly und John Presper Eckert, erbaute den UNIVAC 1(Universal Automatic Computer 1). \n"
           "-Im Jahr 1952 entwickelte Grace den ersten Compiler A-0, da es das Programmieren deutlich benutzerfreundlicher machte. 1955 entwickelte sie dann die erste Programmiersprache FLOW-MATIC, in der Anweisungen verwendet wurden, die englischen Sprache sehr ähnelten.\n"
           "-Basierend auf der Entwicklung des Compilers und der Programmiersprache FLOW-MATIC, entwickelte Grace Hopper mit ihren Kollegen bis 1959 die Programmiersprache COBOL (Common Business Oriented Langage), welche sehr stark an der natürlichen Sprache angelehnt ist und für kaufmännische Anwendungen diente. \n"
           "-1966 ging Hopper vorübergehend in den Ruhestand, kehrte jedoch 1967 in den aktiven Dienst zurück, da auf den Computern der US-Navy verschiedene Programmiersprachen verwendet wurden, was zu einem großen Chaos geführt hat. Dabei sollte Hopper für Ordnung sorgen \n"
           "-Während dieser Zeit stieg sie in der Hierarchie der US Navy auf und erreichte schließlich den Rang eines Rear Admirals. \n"
           "-1971 wurde Hopper Direktorin der Information Systems Technology Office bei der DAPRA (Defense Advanced Research Projects Agency), was eine Behörde des Verteidigungsministeriums der Vereinigten Staaten ist. \n"
           "-Erst 1986 wurde ihr der Dienstgrad Rear Admiral (lower half), der erste der fünf Admiral-Ränge, verliehen, was sie zur sechsten Frau mit einem Admiral-Rang der US-Navy machte. \n"
           "-1986 trat sie aus der Marine aus. \n"
           "-Nach ihrer Zeit bei der Marine, wurde sie Beraterin bei Digital Equipment Corporation (DEC). \n"
           "-Außerdem war sie eine gefragte Rednerin und setzte sich weiterhin für die Förderung von Frauen in der Informatik ein. \n"
           "-Am ersten Januar 1992 starb Grace Hopper in Arlington (Virginia) im Schlaf in einem Alter von 85 Jahren und wurde mit allen militärischen Ehren auf dem Nationalfriedhof Arlington in Virginia beigesetzt. \n\n"
           "### Quellen: \n"
           "Sammet, Jean Ε. (1992): Farewell to Grace Hopper—End of an era!, in: Communications of The ACM, Bd. 35, "
           "Nr. 4, S. 128–131, [online] doi:10.1145/129852.214846.\n"
           "SWRWissen (2023): Grace Hopper und ihr Einfluss auf die IT-Branche, swr.online, [online] "
           "https://www.swr.de/wissen/grace-hopper-und-ihr-einfluss-auf-die-it-branche-100.html. \n"
           "Grace Hopper, Erfinderin des Compilers | Get in IT (o. D.): get in IT, [online] "
           "https://www.get-in-it.de/magazin/arbeitswelt/it-legenden/grace-hopper.\n")
IMAGE_NAME = "Grace_Hopper.jpg"
CONNECTIONS = ["MARK_I", "COMPILERBAU_A-0", "COBOL"]