TITEL = "John von Neumann"
CONTENT = ("-Am 28. Dezember 1903 wurde John von Neumann in Budapest, Österreich-Ungarn, geboren. \n"
"-Schon früh erkannte man, dass John eine außerordentliche mathematische Begabung besitzt. \n"
"-1921 begann von Neumann ein Chemieingenieurwesen Studium in Budapest, wechselte jedoch schnell auf die Universität Berlin und schloss anschließend das Studium mit einem Diplom an der Eidgenössische Technische Hochschule Zürich (kurz ETH) im Jahr 1925 ab. \n"
"-Da er sich auch sehr für die Mathematik und Physik beschäftigte, promovierte John von Neumann 1926 an der Universität in Budapest. Auch Physik studierte er bis dahin nebenbei weiter. \n"
"-1930 begann John von Neumann dann als Gastprofessor in Princeton zu unterrichten. \n"
"-Dort arbeitete er bis 1933, als er Aufgrund der politischen Situation in Europa in die Vereinigten Staaten von Amerika emigriert, sodass er 1937 die US-Amerikanische Staatsbürgerschaft erhält. \n"
"-Während des Krieges arbeitete er an verschiedenen Projekten \n"
"-Ab 1945 entwickelte er Ideen wie die revolutionierende Von-Neumann-Architektur und Grundprinzipien für Rechenanlagen. \n"
"-1952 entwickelte er einem ersten Entwurf des Computers mit flexiblem Speicherprogramm, dem MANIAC 1. \n"
"-Ab 1953 nahm er Teil an wissenschaftlichen und politischen Gremien. Zudem wurde er Präsident des Mathematischen Vereins und Mitglied der Atom-Energie-Kommission. \n"
"-Am 8. Februar 1957 starb John von Neumann in Washington im Alter von 53 Jahren. \n\n"
"Quellen: \n"
"https://www.lernhelfer.de/schuelerlexikon/mathematik/artikel/john-von-neumann#")
IMAGE_NAME = "John_von_Neumann.jpg"