TITEL = "Joseph Weizenbaum"
CONTENT = ("-Am 8. Januar 1923 wird Joseph Weizenbaum in Berlin geboren. \n"
"-Joseph Weizenbaum ging auf das Luisenstädtische Realgymnasium in Berlin, wurde aber Mitte der 1930er Jahre auf die jüdische Knabenschule verwiesen. \n"
"-1936 emigrierte die jüdische Familie als Verfolgte des Nazi-Regimes in die USA. \n"
"-Weizenbaum beginnt nach seinem Schulabschluss 1941 ein Mathematikstudium in Detroit. Dort beteiligte er sich bereits an dem Bau eines Hochschulrechners. \n"
"-1942 bricht er sein Studium aufgrund seines Dienstes bei der US-Army Air Forces im zweiten Weltkrieg ab. \n"
"1946 führte er sein Studium wieder auf und schloss es 1950 mit einem Master ab. Danach beteiligte er sich bereits an dem Bau eines Hochschulrechners. \n"
"-Von 1955 bis 1963 arbeitete er als Systemingenieur bei General Electric und war dort an der Konzeption des ersten computergestützten Banksystems beteiligt. \n"
"-1963 ging er als Dozent ans Massachusetts Institute of Technology (kurz MIT) und forschte an dezentralen Rechnernetzen. \n"
"-1966 schuf er die Software ELIZA mit dem Programm MAD-SLIP, der Vorreiter von Chatbots. Das Programm war ein Meilenstein der künstlichen Intelligenz. \n"
"-Ende der 1960er half er außerdem am Aufbau des Arpanets, dem Vorreiter des Internets. \n"
"-Nach dem Bau von ELIZA begann Weizenbaum kritisch über Computer nachzudenken und wurde zu einem engagierten Gesellschaftskritiker der Informatik. \n"
"-Durch seinen entscheidenden Beitrag in der Informatik wurde er Träger des Bundesverdienstkreuzes und Ehrenmitglied der Gesellschaft für Informatiker. \n"
"-Nachdem er in Rente ging, zog Weizenbaum 1996 wieder nach Berlin. \n"
"-Am 5. März 2008 starb Joseph Weizenbaum an den Folgen eines Schlaganfalls im Alter von 85 Jahren. \n\n"
"Quellen: \n"
"https://gi.de/persoenlichkeiten/joseph-weizenbaum \n"
"https://blog.hnf.de/joseph-weizenbaum-1923-2008/")
IMAGE_DATA = "Joseph_Weizenbaum.jpg"
