TITEL = "Kenneth Lane Thompson (1943)"

CONTENT = ("### Steckbrief:\n"
"-Geboren: 04.02.1943 in New Orleans in Louisiana\n"
	"### Biografie:\n"
		"-Studium der Elektrotechnik machte er an der „University of California“\n"
		"-nach seinem Bachelor- und Masterabschluss 1966 wurde er von Bell Labs (Forschungs- und Entwicklungszweig von AT&T) eingestellt\n"
			"-arbeitete an der Entwicklung des Multics (Multiplexed Information and Computing Service), als Mehrbenutzer-Betriebssystem\n"
			"-scheiterte nach einiger Zeit, wegen Komplexität\n"
		"-Wochen nach der Mondlandung 1969 schrieben er und Dennis Ritchie das Weltraumspiel „Space Travel“\n"
			"-zunächst für Multics und dann für das GECOS-Betriebssystem"
		"-Spiel lief ruckartig, schwer kontrollierbar und teure Laufkosten"
		"-Thompson und Ritchie geben nicht auf"
		"-Aufgrund wenig Speicherplatzes durfte Thompsons Betriebssystem nicht groß sein\n"
		"-innerhalb von vier Wochen entwickelte er sein kleines Betriebssystem Unix und das Spiel konnte laufen\n"
		"-Beitrag: Entwickelte die erste Version des Betriebssystems „Unix“ mit u.a. Dennis Ritchie\n"
		"-Beitrag: Entwickelte die Programmiersprache B mit Ritchie, der Vorläufer von C\n\n"
"### Quellen:\n"
"Geboren.Am (o. D.): Bekannte Informatiker, geboren.am, [online] https://geboren.am/themen/technik/informatiker.\n"
"Informatik, Persönlichkeiten Der (o. D.): Kenneth Lane Thompson, Informatik Aktuell, [online] https://www.informatik-aktuell.de/persoenlichkeiten-der-informatik/kenneth-lane-thompson.html.\n"
           "-Geboren: 04.02.1943 in New Orleans in Louisiana\n"
           "### Biografie:\n"
           "-Studium der Elektrotechnik machte er an der „University of California“\n"
           "-nach seinem Bachelor- und Masterabschluss 1966 wurde er von Bell Labs (Forschungs- und Entwicklungszweig von AT&T) eingestellt\n"
           "-arbeitete an der Entwicklung des Multics (Multiplexed Information and Computing Service), als Mehrbenutzer-Betriebssystem\n"
           "-scheiterte nach einiger Zeit, wegen Komplexität\n"
           "-Wochen nach der Mondlandung 1969 schrieben er und Dennis Ritchie das Weltraumspiel „Space Travel“\n"
           "-zunächst für Multics und dann für das GECOS-Betriebssystem"
           "-Spiel lief ruckartig, schwer kontrollierbar und teure Laufkosten"
           "-Thompson und Ritchie geben nicht auf"
           "-Aufgrund wenig Speicherplatzes durfte Thompsons Betriebssystem nicht groß sein\n"
           "-innerhalb von vier Wochen entwickelte er sein kleines Betriebssystem Unix und das Spiel konnte laufen\n"
           "-Beitrag: Entwickelte die erste Version des Betriebssystems „Unix“ mit u.a. Dennis Ritchie\n"
           "-Beitrag: Entwickelte die Programmiersprache B mit Ritchie, der Vorläufer von C\n"

           "### Quellen:\n"
           "Geboren.Am (o. D.): Bekannte Informatiker, geboren.am, [online] "
		   "https://geboren.am/themen/technik/informatiker.\n"
           "Persönlichkeiten Der Informatik (o. D.): Kenneth Lane Thompson, Informatik Aktuell, [online] "
		   "https://www.informatik-aktuell.de/persoenlichkeiten-der-informatik/kenneth-lane-thompson.html.\n")

IMAGE_NAME = "Ken_Thompson.jpg"

CONNECTIONS = ["DENNIS_RITCHIE", "UNIX", "SPRACHE_B", "BELL_LABS"]
