TITEL = "Konrad Zuse (1910-1995)"
CONTENT = ("-Am 22. Juni 1910 wird Konrad Ernst Otto Zuse in Berlin-Wilmershof geboren. \n"
           "-Als er zwei ist, zieht er mit seiner Familie nach Braunsberg und besucht dort Gymnasium Hosianum \n"
           "-1923, als Konrad in der 9.Klasse war, zog er mit seiner Familie nach Hoyerswerda, wo er zum Reform-Realgymnasium (heute Lessing-Gymnasium) wechselt. Schon früh beginnt er verschiedene Dinge zu erfinden, wofür er teilweise auch Auszeichnungen bekommt. \n"
           "-1928 schließt er sein Abitur ab und beginnt ein Maschinenbaustudium an der Technischen Hochschule Berlin-Charlottenburg (heute Technische Universität Berlin), wechselt dann zur Architektur und studiert schließlich Bauingenieurwesen.  \n"
           "-1933 entwickelt er konkrete Überlegungen auf den Bau eines Computers und entscheidet sich 1934 für die Grundkonzeption seiner programmgesteuerten Rechenmaschine. \n"
           "-1935 schließt er sein Ingenieurstudium mit einem Diplom ab und beginnt bei der Henschel Flugzeug-Werke AG als Statiker \n"
           "-1936 hört er bei Henschel Flugzeug-Werke auf und verfolgt seine Überlegungen zum Bau eines Computers, sodass er seine eigene Erfinderwerkstatt in der Wohnung seiner Eltern errichtete. Zuse erarbeitet ein Aussagenkalkül, also die Aussagenlogik (zum Beispiel: Negation, Disjunktion und Äquivalenz) für duale Rechenautomaten. Dafür kombiniert er frühere Ideen von Leibnitz, Babbage und Boole (, wie zum Beispiel das binäre Zahlensystem von Leibnitz). Dieses Dualsystem wendet er dann auch für digitale Rechenautomaten an. \n"
           "-1937 stellt Zuse das Speicherwerk für seinen Computer fertig, welches voll mechanisch läuft und das Gleitkommarechenwerk, welches ebenfalls ausschließlich mechanisch läuft. \n"
           "-1938 stellt Zuse den Z1 fertig, den damit ersten Computer nach dem Analytical Engine von Charles Babbage und Ada Lovelace. Jedoch funktionierte der Z1 nicht vollständig und Zuse begann mit dem Bau des Z2, welcher teilweise aus Relais gebaut wird.  \n"
           "-1939 wird der Z2 fertiggestellt, jedoch ist Zuse sehr überzeugt von dem Einsatz von Relais, sodass er beim Bau des Z3, den Speicher und das Rechenwerk aus Relais entwickelt. \n"
           "-1941 stellt Konrad Zuse den Z3 fertig, womit er die erste vollautomatische und programmgesteuerte Rechenanlage der Geschichte baut. \n"
           "-Da der Z3 1944 von Bombenangriffen auf Berlin vollständig zerstört wird, bekommt Zuse 25.000 Reichsmark gestellt (heute circa 125.000 Euro), um die bereits 1942 begonnene Z4, welche in Allgäu gesichert werden konnte, fertigzustellen.  \n"
           "-1945 wird die Z4 fertiggestellt und Zuse heiratet in Berlin Gisela Brandes, mit der er später fünf Kinder bekam. \n"
           "-Zuse entwickelte von 1942 bis 1946 den Plankalkül, was eine höhere Programmiersprache war, bei der eine größere Distanz zwischen Programmiersprache und Programmiersprache bestand, sodass verwendete Sprachkonstrukte nicht direkt von den Maschinen verstanden werden konnten. \n"
           "-1949 wird die Zuse KG gegründet, welche 1969 vollständig von der Siemens AG übernommen wurde. \n"
           "-1950 wird die Z4 als funktionierende, programmgesteuerte Rechenanlage an die Eidgenössische Technische Hochschule Zürich (kurz ETH Zürich) geliefert, was es zum ersten kommerziellen Computer weltweit machte. \n"
           "-1955 beginnt die Zuse KG mit der Z11 die Serienanfertigung. Verkauft wird sie hauptsächlich an Universitäten, oder optische Industrien. \n"
           "-1956 erhält Zuse von der Technischen Hochschule Berlin seine Promotion als Doktoringenieur. Außerdem beginnt er mit Entwicklung des Z22, was 1957 fertiggestellt wurde und die erste elektronische Rechenanlage, mit Röhrenrechner in Westdeutschland wurde (da es in der DDR bereits den D1 gab). \n"
           "-1961 stellt Zuse den Graphomat 64 war, welchen er bereits 1956 zu bauen begann. Der Graphomat war ein automatischer Zeichentisch, der automatisch technische Zeichnungen erstellte.  \n"
           "-1964 wird Zuse der Werner-von-Siemens Ring verliehen, was eine sehr Deutsche naturwissenschaftlich-technische Auszeichnung ist. \n"
           "-Auch in den folgenden Jahren, bis zu seinem Tod erhält Zuse sämtliche Auszeichnung und Ehrendoktortitel oder ähnliches, sowohl in Deutschland als auch in anderen Ländern wie Polen, USA oder Italien. \n"
           "-1984 wird das Zuse Informationszentrum Berlin (ZIB) eingeweiht. \n"
           "-Am 18. Dezember 1995 stirbt Konrad Zuse in Hünfeld mit einem alter von 85 Jahren. \n\n"
           "### Quellen: \n"
           "Konrad Zuse - Lebenslauf (o. D.): [online] https://www.nfg24.de/schueler/gdc/zusel.htm. \n"
           "Museum, Stiftung Deutsches Historisches (o. D.): Gerade auf LEMO gesehen: LEMO Biografie, "
           "[online] https://www.dhm.de/lemo/biografie/konrad-zuse. \n"
           "Informatik - für Schüler und Studenten (2021): Plankalkül Definition & Erklärung | Informatik Lexikon, "
           "Informatik - für Schüler und Studenten, [online] https://www.informatik-verstehen.de/lexikon/plankalkuel/.")
IMAGE_NAME = "Konrad_Zuse.jpg"
CONNECTIONS = ["Z3", "ZUSE_KG", "ZUSE_INSTITUT_BERLIN"]
