TITEL = "Niklaus Wirth (1934)"

CONTENT = ("### Steckbrief:\n"
"-Geboren: 15.02.1934 in Winterthur in der Schweiz\n\n"
"-Geboren: 15.02.1934 in Winterthur in der Schweiz\n"
"### Biografie:\n"
"-studierte Elektrotechnik mit dem Schwerpunkt Elektronik an der ETH Zürich bis 1959\n"
"-bekam seinen Master von der „Laval University“ in Kanada im Jahr 1960\n"
"-er promovierte an der „University of California“ in Berkeley 1963\n"
	"-dort entstand seine erste Programmiersprache Euler\n"
"-nach Assistenzprofessuren an der „Standford University“ und der Universität Zürich ging er 1968 an die ETH zurück\n"
	"-Lehrstuhl für Software-Engineering bis 1999\n"
"-Entwarf und implementierte Pascal von 1968 bis 1972\n"
"-Arbeitete als Assistent-Professor für Informatik and der „Standford University“ nach dem ETH-Studium\n"
"-ab 1968 ist er Professor für Informatik an der ETH Zürich\n"
"-zwei Sabbat-Jahre verbringt er bei „Xerox Corporation“ in Kalifornien\n"
"-Hauptinteresse liegt in Software-Engineering und Entwicklung von Programmiersprachen\n"
"-um 1960 beteiligte er sich an der Entwicklung von ALGOL\n"
"-Hauptbeitrag: die populäre Programmiersprache „Pascal“ wurde von ihm entwickelt 1970\n"
		"-führte „Pascal“ an der ETH-Zürich für die Lehre ein\n"
		"-fand unerwartete Akzeptanz bei professionellen Anwendungen\n"
"-1980 folgten die Weiterentwicklung Modula 2 sowie die objektorientierte Variante Oberon\n"
	"-entwickelte die Computersysteme „Lilith“ (1980) und „Ceres“ (1986) mit den zugehörigen Betriebssystemen\n" 
		"-Versuche, diese Workstations kommerziell zu vermarkten, scheiterten\n"
	"-danach widmete er sich im Rahmen von Lilith und Ceres auch dem Design programmierbarer ICs\n"
	"-nach seiner Pensionierung 1999 ging er seinem Jugendhobby des Modellflugs wieder nach\n\n"
"### Quellen:\n"
"Geboren.Am (o. D.): Bekannte Informatiker, geboren.am, [online] https://geboren.am/themen/technik/informatiker.\n"
"Geboren.Am (o. D.): Bekannte Informatiker, geboren.am, [online] https://geboren.am/themen/technik/informatiker.\n"
"Niklaus Wirth - Winterthur Glossar (o. D.): [online] https://www.winterthur-glossar.ch/niklaus-wirth.\n")

IMAGE_NAME = "Niklaus_Wirth.jpg"

CONNECTIONS = ["SPRACHE_PASCAL","LILITH","CERES","SPRACHE_OBERON","SPRACHE_MODULA2","PROGRAMMIERBARE_ICS","SPRACHE_ALGOL","SPRACHE_EULER"]