TITEL = ("Bekannte Informatiker\n"
     "& deren Beiträge")

CONTENT = ""

CONNECTIONS = ["ALAN_TURING", "ALONZO_CHURCH", "DENNIS_RITCHIE", "JOHN_PRESPER_ECKERT", "JOHN_WILLIAM_MAUCHLY", "KENNETH_LANE_THOMPSON", "NIKLAUS_WIRTH", "RAY_TOMLINSON", "ROBERT_CAILLIAU", "TIM_BERNERS_LEE"]