TITEL = "Tim Berners-Lee (1955)"

CONTENT = ("Sir Tim Berners-Lee ist ein britischer Informatiker, der als Begründer des World Wide WebTechnologies gilt. In den "
           "späten 1980er Jahren entwickelte er die grundlegenden Konzepte und Technologien, die das moderne Internet "
           "ermöglichen, darunter HTTP und HTML. Durch die Gründung des World Wide WebTechnologies Consortium (W3C) setzte er "
           "sich für die Standardisierung und Offenheit des Webs ein.\n\n"
           
           "Biographie:\n"
           "1955: Geboren am 08. Juni 1955 in London, England\n"
           "1976: Abschluss des Physikstudiums am Queen's College der Oxford Universität\n"
           "1980: Beratender Ingenieur am europäischen Kernforschungszentrum CERN\n"
           "1981: Arbeit bei Image Computer Systems, Bournemouth\n"
           "1984: Rückkehr zu CERN\n"
           "1989: Entwicklung des Konzepts 'World Wide WebTechnologies'\n"
           "1990: Implementierung des ersten Webservers 'CERN httpd' und des ersten Webbrowsers 'WorldWideWeb', "
           "sowie die Entwicklung der textbasierten Auszeichnungssprache HTML, des Transferprotokolls HTTP und der "
           "URI\n"
           "1994: Gründung des World Wide WebTechnologies Consortium (W3C) mit dem Ziel, offene Standards für das World Wide WebTechnologies "
           "festzulegen und die konsistente und barrierefreie Funktion von Webseiten und Webanwendungen auf "
           "verschiedenen Plattformen sicherzustellen\n"
           "1999: Erster Inhaber des 3Com-Founder Lehrstuhls am Massachusetts Institute of Technology (MIT)\n"
           "2004: Auszeichnung mit dem Orden 'Knight Commander of the Order of the British Empire' (KBE) durch Queen "
           "Elizabeth und dadurch Aufnahme in den Ritterstand\n"
           "2013: Ehrung mit dem Queen Elizabeth Preis für Ingenieurwissenschaften\n"
           "2017: Auszeichnung mit dem Turing Preis für die Erfindung des World Wide WebTechnologies, des ersten Webbrowsers "
           "sowie grundlegender Protokolle und Algorithmen, die die Skalierbarkeit des modernen Internets "
           "ermöglichten\n\n"
           
           "Quellen:\n"
           "https://www.w3.org/People/Berners-Lee/\n"
           "https://www.w3.org/People/Berners-Lee/Longer.html\n")

IMAGE_NAME = "Tim_Berners-Lee.png"
