TITEL = "Z3"
CONTENT = ("-1938 begann Konrad Zuse nach dem Bau des Z1 und Z2 mit dem Bau des Z3. \n"
"-Der Z3 konnte 64 Wörter speichern und brauchte 3 Sekunden um eine Berechnung, wie eine Division oder Multiplikation durchzuführen und circa 0,8 Sekunden für eine Addition. \n"
"-Dabei wurde die Eingabe und Ausgabe mittels dezimaler Gleitkommazahlen gelöst. Das Rechenwerk funktionierte ebenfalls mit einem Gleitkommrechenwerk und zudem in binär. \n"
"-Der Z3 arbeitete mit gerade einmal 5 Hertz, also Operationen pro Sekunde. Zum Vergleich heutzutage arbeiten die Computer mit Milliarden Hertz (Gigahertz). \n"
"-Der Z3 bestand aus über 2500 Relais, also Spulen, durch die Strom fließt, die dann ein magnetisches Feld erzeugen lassen, wodurch ein Anker angezogen wird und sich zwei Kontaktfedern öffnen oder schließen können. Der Z3 wog ungefähr eine Tonne. Zudem nutzte der Z3 genau wie später auch der Mark 1 Lochstreifen, auf die Informationen in Form von ausgestanzten Löchern ausgegeben werden konnten. \n"
"-Fertiggestellt und anderen Wissenschaftlern (unter anderem: Alfred Teichmann und Curt Schmieden) vorgestellt wurde der Z3 1941, womit Konrad Zuse den ersten offiziellen Computer rausbrachte. \n"
"-Da es während des zweiten Weltkrieges einen Bombenangriff auf Berlin gab, wurde der Z3 1944 leider vollständig zerstört. Daher wurde Geld in den darauffolgenden Z4 investiert. \n"
"-2010 wurde der Z3, 100 Jahre nach Konrad Zuses Geburtstag, nachgebaut und steht im Konrad-Zuse-Museum. \n\n"
"### Quellen: \n"
"Stoller, Detlef (2022): Der erste Computer der Welt: Z3 von Konrad Zuse fand damals kaum Beachtung, ingenieur.de - Jobbörse und Nachrichtenportal für Ingenieure, [online] https://www.ingenieur.de/technik/produkte/konrad-zuses-z3-computer-welt-80/ \n"
"Konrad Zuse - Lebenslauf (o. D.): [online] https://www.nfg24.de/schueler/gdc/zusel.htm")
IMAGE_NAME = "Z3.JPG"