TITEL = "Arpanet"

CONTENT = ("-der erste Schritt in Richtung Internet war 1957\n"
		"->Gründung der „Advanced Research Projects Agency“ (ARPA) im Verteidigungsministerium der USA\n"
	"-in den Folgejahren langsamer Fortschritt, da kein konkretes Konzept vorhanden war\n"
"-Initiierung des Projekts im Jahr 1968 von Forschern unter Leitung des Verteidigungsministeriums der USA und des „Masschusetts Institute of Technology“ (MIT)\n"
	"-Ziel war es ein dezentrales Computer-Netzwerk und die Vernetzung von US-Universitäten\n"
		"->sollte atombombensicher sein und bei Ausfällen noch weiter funktionieren\n"
	"-Arpanet war technisch noch weit entfernt von modernen Standards\n"
	"-mittels Verbindung über Telefonleitungen wurde die Kommunikation über größere Entfernung ermöglicht\n"
	"-1961 kam die Idee von Datenübertragung in Pakete durch das Netz\n"
"->die Paketvermittlung (Paket Switching) ermöglichte die Entwicklung in Richtung des heutigen Internets\n"
		"-> Daten werden in Pakete unterteilt und häppchenweise übertragen\n"
	"-vor allem wurde der Arpanet-Standard durch Unix und der Programmiersprache C geprägt\n"
	"-erstes WAN der Welt kam 1965 durch eine direkte Verbindung der Rechner TX-2 (MIT) und Q-32 (System Development Corporation)\n"
	"-1967 wurde dann das erste Designpapier über ARPANET durch Lawrence G. Roberts veröffentlicht\n"
	"-1968 wurde das Konzept der paketvermittelnden Netze der ARPA präsentiert\n"
	"-bis das Arpanet realisiert wurde, brauchte es etwa ein Jahr\n"
	"-beauftragt wurde „BBN Technologies“\n"
		"->entwickelte den „Interface Message Processor“\n"
	"-die Verbindung via Modem ermöglichte eine Netzgeschwindigkeit von 50Kbit/s\n"
		"->mit heute nicht mehr vergleichbar, bildete aber die Grundlage für die Netzwerktechnologie des Internets\n"
	"-etwa neun Monate wurden benötigt für die Entwicklung von Hard- und Softwarekomponenten sowie die Paketvermittlung an sich und sie zu implementieren\n"
	"-das ARPANET wurde schließlich 1969 geboren und bestand aus der Verbindung von vier Rechnern der „University of California at Los Angeles“, „Stanford Research Institute“, „UCSB“ und University of Utah“\n"
	"-ein weiterer Meilenstein wurde 1983 erreicht mit der Verwendung der TCP-/IP-Protokolle\n"
	"-in den nächsten Jahren wurden immer mehr Rechner an das ARPANET angeschlossen\n"
	"-1973 wurde auch die Universität „Collage of London“ drangebunden, was die erste internationale Verbindung war\n"
	"-Vint Cerf und Bob kahn veröffentlichten „A Protocol for Paket Network Intercommunication“\n"
		"->beschreibt das Design des „Transmission Control Programs“ (TCP)\n"
	"Quellen:\n"
"- https://www.it-business.de/was-ist-arpanet-a-848892/\n"
"- https://mcse.xn--krbel-jua.at/links/grundlagen/netzwerk/arpanet.htm\n")

IMAGE_NAME = ""