TITEL = "Hypertext Markup Language (HTML)"

CONTENT = ("HTML ist eine textbasierte Auszeichnungssprache, die vor allem im Kontext des World Wide Webs verwendet "
           "wird. Die erste HTML-Spezifikation wurde von Tim Berners-Lee im Jahre 1992 veröffentlicht. Ziel war es, "
           "eine für alle Machines verständliche Sprache für die globale Veröffentlichung von Informationen zu "
           "schaffen. Die Standards für HTML werden vom 'World Wide Web Consortium' (W3C) festgelegt. Zusammen mit "
           "der 'Web Hypertext Application Technology Working Group' (WHATWG) entwickelt W3C HTML weiter. Die "
           "aktuelle Version ist HTML5.\n\n"

           "Sprachelemente\n"
           "1. Dokumenttypdefinition (DTD):  formale Spezifikation, die die Struktur und Syntax von XML-Dokumenten "
           "definiert\n"
           "2. Dokumenttypdeklarationen: definiert die HTML-Version und referenziert die DTD (ausgenommen HTML5)\n"
           "3. Elemente: Repräsentieren Strukturen oder gewünschtes Verhalten. Sie bestehen üblicherweise aus einem "
           "Start-Tag (z.B.: \"<HTML>\"), einem End-Tag (z.B.: \"</HTML>\") und einem beliebigen Inhalt. Abhängig von "
           "der DTD-Spezifikation kann das End-Tag bei Elementen auch weggelassen werden oder der Inhalt leer sein.\n"
           "4. Attribute: Eigenschaften eines Elements, die als Key-Value-Paare vor dem \">\"-Zeichen des jeweiligen "
           "Start-Tags stehen\n"
           "5. Zeichenreferenzen: numerische oder symbolische Namen für Zeichen. Sie beginnen mit einem \"&\" und "
           "enden mit einem Semikolon. Beispiele: \"&lt;\" ist die Zeichenreferenz für  \"<\", \"&gt\" ist die "
           "Zeichenreferenz für \">\"\n"
           "6. Kommentare: Anmerkungen oder Erläuterungen zum HTML-Code, die nicht interpretiert werden. Sie beginnen "
           "mit \"<!--\" und enden mit \"-->\"\n\n"
           
           "Typischer Aufbau\n"
           "1. HTML-Dokumente beginnen mit der \"<!DOCTYPE html>\"-Deklaration (HTML5)\n"
           "2. Danach folgt der \"<HEAD>\"-Bereich mit Metainformationen wie Titel, Zeichensatz und den "
           "Ansichtseinstellungen\n"
           "3. Der \"<BODY>\"-Bereich stellt den eigentlichen Inhalt der Webseite dar. Er besteht aus Textelementen, "
           "Listen, Verweisen, Formularen und Strukturelementen.\n\n"

           "Beispiel (HTML5):\n"
           "<!DOCTYPE html>\"\n"
           "<HTML>\n"
           "    <HEAD>\n"
           "        <TITLE>My first HTML document</TITLE>\n"
           "        <META http-equiv=\"content-type\"\\\n"
           "              content=\"text/html;\\\n"
           "              charset=utf-8\"/>\n"
           "        <META name=\"viewport\"\\\n"
           "              content=\"width=device-width,\\ \n"
           "              initial-scale=1.0\"/>\n"
           "    </HEAD>\n"
           "    <BODY>\n"
           "        <HEADER>\n"
           "            <H1 id=\"section1\">\n"
           "            This is an identified heading thanks to the id attribute\n"
           "            </H1>\n"
           "        </HEADER>\n"
           "        <P>Hello world!\n"
           "    </BODY>\n"
           "</HTML>\n\n"

           "Quellen:\n"
           "http://homepages.cs.ncl.ac.uk/brian.randell/Seminars/92.pdf\n"
           "https://www.immagic.com/eLibrary/ARCHIVES/SUPRSDED/W3C/W980424S.pdf\n"
           "https://html.spec.whatwg.org/multipage/\n")

IMAGE_NAME = "HTML.png"
