TITEL = "HTTP"

CONTENT = ("### Eigenschaften:\n"
           "-„http“ steht für „Hypertext Transfer Protocol“\n"
           "-es ist ein zustandsloses Protokoll für die Übertragung von Daten in IP-Netzwerken\n"
           "-Hauptanwendung: Übertragung von Internetseiten zwischen Webserver und Webbrowser\n"
           "-es ist nicht auf Webseiten beschränkt, sondern wird auch für andere Anwendungen genutzt\n\n"
           "### Entwicklung:\n"
           "-Entwicklung begann 1989\n"
           "-es gibt folgende Versionen: HTTP/1.0 (1996), HTTP/1.1 (1999), HTTP/2 (2015)\n"
           "-Anwendungsschicht im Schichtenmodell (Layer 7)\n\n"
           "### Funktionsweise:\n"
           "-Client-Server-Prinzip: Webbrowser (Client), Webserver (HTTP-Server)\n"
           "-beim Abrufen einer Website im Browser sendet HTTP-Request an Port 80 des Servers\n"
           "-Antwort erfolgt mit einer Response-Nachricht\n"
           "-Kommunikation basiert auf Textformat, Request- und Response-Nachrichten enthalten Header und Daten\n"
           "-hauptsächlich für die Übertragung von Webseiten im Internet\n"
           "-nicht auf Hypertext beschränkt, kann für den Austausch beliebiger Daten genutzt werden\n"
           "-verwendet TCP (Transmission Control Protocol) für zuverlässige Datenübertragung\n\n"
           "### Sicherheitsaspekte von HTTP:\n"
           "-überträgt Informationen unverschlüsselt im Klartext\n"
           "-HTTPS (Hypertext Transfer Protocol Secure) als verschlüsselte Variante\n"
           "-Authentifizierung, Ende-zu-Ende-Verschlüsselung mit Zertifikaten\n"
           "-User-Authentifizierung und Kompressionsmöglichkeit sind Optionen\n"
           "Port 443 für HTTPS, erkennbar an 'https://' in der URL\n\n"
           "### Quellen:\n"
           "Donner, Andreas/Stefan Luber (2019): Was ist HTTP (Hypertext Transfer Protocol)?, in: IP-Insider, 19.03.2019, [online] https://www.ip-insider.de/was-ist-http-hypertext-transfer-protocol-a-691181/#:~:text=Das%20Hypertext."
           "%20Transfer%20Protocol%20arbeitet,mit%20einer%20Response%2DNachricht%20beantwortet (Stefan Luber, 2018)\n")

IMAGE_NAME = ""

CONNECTIONS = ["WORLD_WIDE_WEB", "TIM_BERNERS_LEE", "WORLD_WIDE_WEB_CONSORTIUM"]
